### ISSUE TITLE
copy/paste

### ISSUE THREAD

**Issue by coderofsalvation** [sdether/josh.js#28]
scenario: in another browsertab I have an url..I select the url, rightclick *copy*. I try to paste it into josh.js but it doesnt work on chrome 41.0

any ideas?

I tried:

      $("span.cursor").bind('paste', function(f) {
         console.dir(f);
      }); 

Which got triggered, but I was unsuccesful in getting the data.
Googled a bit, and decided to ask here before getting messy with hidden textareas :)

**Comment by coderofsalvation** [comment]
nvm, just solved my problem using the following hack:

# readline.js: added public function addText()

      + }
      + addText: function(str) {
      + //_line.text = str;
      + //_line.cursor = str.length+1;
      + //self.refresh();
      + _readline.addText(str);
      +  self.refresh();
      + }
    };

    function id(id) {
      return "#"+id;
    }

# onDomReady(): allow copy/paste

      $("*").pastableNonInputable();
      $("*").on('pasteText', function(ev, data) {
         console.dir(data);
         shell.addText(data.text);
      }); 

using [paste.js](https://github.com/layerssss/paste.js/issues/1)

boom! as said its a hack..but it works for me on chrome

**Comment by sdether** [comment]
Interesting. So addText is just a function added to readline to be able to add text outside of its key event loop?

**Comment by coderofsalvation** [comment]
exactly. Personally I could not find a (public) readline function which
does that.
(Doesnt mean there isnt any)
Pasting text directly to the DOM resulted in readline erasing the paste, to
simply redraw the readline buffer.

**Comment by sdether** [comment]
Yeah, there isn't such a facility, since readline really was just an event processor. I think what you did makes sense and I'll take a look whether i can take that it verbatim, or if there some other things it should do. Haven't looked at the processing loop in a while

**Comment by coderofsalvation** [comment]
I see thank you for your thoughts.
Maybe there's a way to decorate readline with a public function without
having to edit readline.js .
I'll let you know when I discover something new.
