### ISSUE TITLE
Example does not work properly

### ISSUE THREAD

**Issue by Ri1a** [sdether/josh.js#43]
Hey

So, I've downloaded the repo, but the example isn't working properly. I can't type in any commands, just can open the shell with **~**, but then nothing. No errors.

Any suggestions?

**Comment by Ri1a** [comment]
Fixed it.

**Comment by sdether** [comment]
Curious what the problem was. I haven't touched Josh.js in a while, but would appreciate any feedback on setup pitfalls that might be worth documenting

**Comment by Ri1a** [comment]
Just needed to rename the js folder to javascripts. I'm sorry for that one:D

But when I want to run this on my github page it doesn't works properly. Don't see any bash like command line, but the windows is there...
